In [1]:
import numpy as np
import matplotlib.pylab as plt
from numpy import random
from pprint import pprint as pp

# Arrays

In [98]:
list_1 = [1, 2, 3, 4, 5]
np_arr_1 = np.array(list_1, dtype=np.int8)  # byte
np_arr_1

m_list_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np_m_arr_1 = np.array(m_list_1)
np_m_arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
np_m_arr_1.size

9

In [100]:
np_m_arr_1.shape

(3, 3)

In [101]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
np.linspace(0, 5, 5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [103]:
np.zeros(4)

array([0., 0., 0., 0.])

In [104]:
np.zeros((2, 3))  # 2 rows, 3 cols

array([[0., 0., 0.],
       [0., 0., 0.]])

In [105]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [106]:
np_arr_2 = np.array(range(1, 7))
print(np_arr_2, np_arr_2.dtype)

[1 2 3 4 5 6] int64


# Random Arrays

In [107]:
np.random.randint(10, 50, size=(2, 3))  # int

array([[21, 47, 12],
       [20, 10, 33]])

In [108]:
np.random.uniform(10, 50, size=(2, 3))  # float 

array([[45.07851489, 40.44751142, 27.41077812],
       [35.50687998, 46.68806189, 30.90374869]])

In [109]:
np.random.random(size=(2, 3))  # b/w 0 and 1 floats

array([[8.59322408e-01, 4.89783460e-01, 9.99958282e-01],
       [8.57635198e-01, 2.07635944e-01, 8.94711461e-04]])

In [110]:
np.random.randn(2, 5)  # std normal distribution

array([[-0.35637064,  1.04288942, -0.21451586, -0.37839136,  0.21533289],
       [-0.11853127, -0.61170646, -0.08584108, -1.3835178 , -0.00283385]])

In [214]:
random.choice(np_arr_1)  # random choice from 1D array

5

# Slicing 

In [111]:
np_m_arr_1[0, 0] = 2
np_m_arr_1.itemset((0, 1), 1)
np_m_arr_1

array([[2, 1, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
np.take(np_m_arr_1, [0, 3, 6])

array([2, 4, 7])

In [113]:
np.put(np_m_arr_1, [0, 3, 6], [10, 10, 10])
np_m_arr_1

array([[10,  1,  3],
       [10,  5,  6],
       [10,  8,  9]])

In [114]:
np_arr_1[::2]

array([1, 3, 5], dtype=int8)

In [115]:
np_m_arr_1[:,1]  # rows, cols

array([1, 5, 8])

In [116]:
np_m_arr_1[::-1]  # flip NOT transpose

array([[10,  8,  9],
       [10,  5,  6],
       [10,  1,  3]])

In [117]:
evens = np_m_arr_1[np_m_arr_1%2==0]
odds = np_m_arr_1[np_m_arr_1%2==1]

# Reshaping

In [118]:
np_m_arr_1

array([[10,  1,  3],
       [10,  5,  6],
       [10,  8,  9]])

In [119]:
np_m_arr_1.reshape((1, 9))
# or 
np.resize(np_m_arr_1, (1, 9))

array([[10,  1,  3, 10,  5,  6, 10,  8,  9]])

In [120]:
np_m_arr_1.transpose()

array([[10, 10, 10],
       [ 1,  5,  8],
       [ 3,  6,  9]])

In [121]:
np_m_arr_1.swapaxes(0, 1)  # transpose for 2 demensionals

array([[10, 10, 10],
       [ 1,  5,  8],
       [ 3,  6,  9]])

In [122]:
np_m_arr_1.flatten()  # if you don't care to know reshape length

array([10,  1,  3, 10,  5,  6, 10,  8,  9])

In [123]:
np_m_arr_1.flatten('F')  # by col

array([10, 10, 10,  1,  5,  8,  3,  6,  9])

In [125]:
np_m_arr_1.sort(axis=1)
np_m_arr_1

array([[ 1,  3, 10],
       [ 5,  6, 10],
       [ 8,  9, 10]])

# Stacking & Splitting

In [148]:
ss_arr_1 = np.random.randint(10, size=(2, 2))  # 0 to but not including 10
ss_arr_2 = np.random.randint(10, size=(2, 2))  # 0 to but not including 10

ss_arr_1, '----' * 10, ss_arr_2 

(array([[3, 0],
        [8, 2]]),
 '----------------------------------------',
 array([[4, 1],
        [7, 8]]))

In [149]:
np.vstack((ss_arr_1, ss_arr_2))  # or np.column_stack for 2D

array([[3, 0],
       [8, 2],
       [4, 1],
       [7, 8]])

In [150]:
np.hstack((ss_arr_1, ss_arr_2))  # or np.row_stack for 2D

array([[3, 0, 4, 1],
       [8, 2, 7, 8]])

In [165]:
np.delete(ss_arr_1, 0, axis=0)  # complete row or col; 0 or 1

array([[8, 2]])

In [196]:
np.vsplit(np.hstack((ss_arr_1, ss_arr_2)), 2)

[array([[3, 0, 4, 1]]), array([[8, 2, 7, 8]])]

In [202]:
np.hsplit(np.hstack((ss_arr_1, ss_arr_2)), (1, 2))

[array([[3],
        [8]]),
 array([[0],
        [2]]),
 array([[4, 1],
        [7, 8]])]

# Copy

In [207]:
np_m_arr_1.copy()  

array([[ 1,  3, 10],
       [ 5,  6, 10],
       [ 8,  9, 10]])

# Basic Math

In [244]:
arr_1 = np.array(range(2, 11, 2)) 
arr_2 = np.array(range(1, 10, 2))
print(arr_1)
print(arr_2)
print()
print(arr_1 - arr_2)
print(arr_1 + arr_2)
print(arr_1 / arr_2)
print(arr_1 % arr_2)

[ 2  4  6  8 10]
[1 3 5 7 9]

[1 1 1 1 1]
[ 3  7 11 15 19]
[2.         1.33333333 1.2        1.14285714 1.11111111]
[0 1 1 1 1]


In [245]:
arr_1.sum()

30

In [246]:
arr_1.min(axis=0)

2

In [248]:
a = np.array([[2, 2, 5], [2, 64, 90], [4, 3, 3]])
print(a)
a.min(1)  # min of each col

[[ 2  2  5]
 [ 2 64 90]
 [ 4  3  3]]


array([2, 2, 3])

In [249]:
np.remainder(arr_2, arr_1)

array([1, 3, 5, 7, 9])

In [250]:
np.power(arr_1, arr_2)

array([         2,         64,       7776,    2097152, 1000000000])

In [252]:
np.absolute(arr_1), np.exp(arr_1), np.log2(arr_1)

(array([ 2,  4,  6,  8, 10]),
 array([7.38905610e+00, 5.45981500e+01, 4.03428793e+02, 2.98095799e+03,
        2.20264658e+04]),
 array([1.        , 2.        , 2.5849625 , 3.        , 3.32192809]))